(() => {
  const KEY = 'blocktrace-agent-memory-v2';
  const state = { observations:0, style:'balanced', lastRole:'hacker' };
  const memory = JSON.parse(localStorage.getItem(KEY) || '{"runs":0,"styles":{},"roles":{}}');
  const save=()=>localStorage.setItem(KEY,JSON.stringify(memory));
  const api=()=>window.Blocktrace;
  function classify(s){const elapsed=Math.max(1,s.elapsed),speed=s.distance/elapsed;if(s.shards>=2&&elapsed<50)return'rusher';if(speed>1.35&&s.shards<2)return'explorer';return'balanced'}
  function adapt(s){const a=api();if(!a||!s.started||s.complete)return;const next=classify(s);if(next!==state.style){state.style=next;memory.styles[next]=(memory.styles[next]||0)+1;save();const msg={explorer:'AGENT ADAPT // curiosity detected. Side routes now prioritized.',rusher:'AGENT ADAPT // high-velocity trace detected. Shortcut signals acquired.',balanced:'AGENT ADAPT // behavior calibrated. Strongest city signal selected.'}[next];a.log(msg,'good')}const role=s.role||'hacker';const mission=role==='hacker'?{explorer:'Scout the city // extract encrypted shards',rusher:'Fast trace // extract 3 shards',balanced:'Follow the Agent // extract encrypted shards'}[state.style]:{explorer:'Sweep the districts // secure compromised nodes',rusher:'Rapid response // secure 3 nodes',balanced:'Follow the Agent // stabilize compromised nodes'}[state.style];if(s.shards<3)a.setMission(mission)}
  function pulse(){const a=api();if(!a)return;const s=a.getState();if(!s.started||s.complete)return;state.observations++;adapt(s);if(state.observations%3===0&&s.shards<3){const signals=['MEMPOOL FLUX // route prediction updated','PROTOCOL NOISE // Agent filtering simulated threats','NODE ECHO // alternate district path mapped','CHAIN PULSE // city state synchronized'];a.log(signals[Math.floor(Math.random()*signals.length)])}}
  function boot(){const a=api();if(!a)return setTimeout(boot,50);a.on('start',d=>{state.lastRole=d.role||'hacker';memory.runs=(memory.runs||0)+1;memory.roles[state.lastRole]=(memory.roles[state.lastRole]||0)+1;save();a.log('AGENT CORE // city behavioral model online','good');a.log(`AGENT MEMORY // ${memory.runs} trace(s) remembered`)});a.on('shardRecovered',d=>a.log(`AGENT OBSERVE // shard ${d.count}/3. District route model updated.`));a.on('nodeSecured',d=>a.log(`AGENT OBSERVE // node ${d.count}/3. Defense model updated.`));a.on('beaconSync',()=>a.log('AGENT DECISION // city beacon accepted. Confidence increased.'));a.on('complete',d=>a.log(`AGENT CORE // trace complete in ${Math.round(d.elapsed)}s. Session memory saved.`,'good'));setInterval(pulse,3000)}boot();
})();
