const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');
const missionEl=document.getElementById('mission'),hintEl=document.getElementById('hint'),syncEl=document.getElementById('sync'),shardsEl=document.getElementById('shards'),levelEl=document.getElementById('level'),feedEl=document.getElementById('feed'),statusEl=document.getElementById('status');
let W,H,started=false,complete=false,last=0,keys={},mouseDown=false,turn=0;
const map=["111111111111","100000000001","101111011101","100001010001","101101010101","100100010001","100111110101","100000000101","101111010101","100000010001","101111111101","100000000001","111111111111"];
const shards=[{x:2.5,y:2.5,taken:false},{x:9.5,y:3.5,taken:false},{x:5.5,y:10.5,taken:false}];
const vault={x:10.5,y:10.5};const beacon={x:9.5,y:9.5};
const p={x:1.8,y:1.8,a:0};let sync=0,level=1,startedAt=0,distanceTravelled=0,interactionCount=0;
const agentListeners={};
function emit(name,detail={}){(agentListeners[name]||[]).forEach(fn=>fn(detail));window.dispatchEvent(new CustomEvent(`blocktrace:${name}`,{detail}));}
window.Blocktrace={getState:()=>({started,complete,sync,level,shards:shards.filter(s=>s.taken).length,position:{x:p.x,y:p.y},angle:p.a,distance:distanceTravelled,interactions:interactionCount,elapsed:startedAt?(performance.now()-startedAt)/1000:0}),on:(name,fn)=>{(agentListeners[name]??=[]).push(fn);return()=>agentListeners[name]=agentListeners[name].filter(x=>x!==fn)},setMission:(text)=>missionEl.textContent=text,setHint:(text)=>hintEl.textContent=text,log};
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=innerWidth;H=innerHeight}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('mousedown',()=>{mouseDown=true;canvas.requestPointerLock?.()});addEventListener('mouseup',()=>mouseDown=false);addEventListener('mousemove',e=>{if(started&&!complete&&document.pointerLockElement===canvas)p.a+=e.movementX*.0022});
function wall(x,y){const ix=Math.floor(x),iy=Math.floor(y);return iy<0||iy>=map.length||ix<0||ix>=map[0].length||map[iy][ix]==='1'}
function move(dx,dy){const r=.2;const oldX=p.x,oldY=p.y;if(!wall(p.x+dx+r,p.y)&&!wall(p.x+dx-r,p.y))p.x+=dx;if(!wall(p.x,p.y+dy+r)&&!wall(p.x,p.y+dy-r))p.y+=dy;distanceTravelled+=Math.hypot(p.x-oldX,p.y-oldY)}
function interact(){if(!started||complete)return;interactionCount++;let near=shards.find(s=>!s.taken&&Math.hypot(s.x-p.x,s.y-p.y)<.9);if(near){near.taken=true;sync+=25;level=Math.min(4,1+shards.filter(s=>s.taken).length);log('SHARD RECOVERED // encrypted payload synced','good');emit('shardRecovered',{count:shards.filter(s=>s.taken).length,position:{x:near.x,y:near.y}});updateHud();return}if(Math.hypot(beacon.x-p.x,beacon.y-p.y)<1){log('AGENT BEACON // route recalculated','good');sync=Math.min(95,sync+10);emit('beaconSync',{sync});updateHud();return}if(Math.hypot(vault.x-p.x,vault.y-p.y)<1&&shards.every(s=>s.taken)){complete=true;document.getElementById('complete').classList.remove('hidden');document.getElementById('completeText').textContent=`Trace stabilized at ${sync}% sync. The Agent recovered all three shards and opened the Genesis Vault.`;emit('complete',{sync,elapsed:startedAt?(performance.now()-startedAt)/1000:0})}}
function log(t,c=''){const d=document.createElement('div');d.className=c;d.textContent='> '+t;feedEl.prepend(d);while(feedEl.children.length>5)feedEl.lastChild.remove()}
function updateHud(){syncEl.textContent=Math.round(sync)+'%';shardsEl.textContent=shards.filter(s=>s.taken).length+' / 3';levelEl.textContent=level;if(shards.every(s=>s.taken)){missionEl.textContent='Open the Genesis Vault';hintEl.textContent='Reach the gold terminal and press E.'}else{missionEl.textContent='Recover protocol shards';hintEl.textContent=`${3-shards.filter(s=>s.taken).length} shard(s) remain. Follow the beacons.`}}
function start(){started=true;startedAt=performance.now();document.getElementById('start').classList.add('hidden');statusEl.textContent='SYNCED';log('AGENT ONLINE // autonomous route planner initialized','good');log('MISSION 01 // recover 3 protocol shards');emit('start');canvas.requestPointerLock?.();requestAnimationFrame(loop)}
document.getElementById('startBtn').onclick=start;document.getElementById('againBtn').onclick=()=>location.reload();
function update(dt){if(!started||complete)return;let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),r=(keys.d?1:0)-(keys.a?1:0);if(keys.arrowleft)p.a-=dt*1.8;if(keys.arrowright)p.a+=dt*1.8;let sp=keys.shift?3.5:2.2;let l=Math.hypot(f,r)||1;f/=l;r/=l;move((Math.cos(p.a)*f-Math.sin(p.a)*r)*sp*dt,(Math.sin(p.a)*f+Math.cos(p.a)*r)*sp*dt);if(sync<100)sync=Math.min(100,sync+dt*1.2);if(Math.hypot(beacon.x-p.x,beacon.y-p.y)<1.2&&!shards.every(s=>s.taken)){hintEl.textContent='Beacon acquired. Press E to let the Agent resync the route.'}}
function render(){ctx.clearRect(0,0,W,H);let horizon=H*.52;let sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#030711');sky.addColorStop(1,'#0b1d2a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,horizon);let floor=ctx.createLinearGradient(0,horizon,0,H);floor.addColorStop(0,'#111923');floor.addColorStop(1,'#020408');ctx.fillStyle=floor;ctx.fillRect(0,horizon,W,H-horizon);const rays=Math.ceil(W/2),fov=Math.PI/3;for(let i=0;i<rays;i++){let cam=(i/rays-.5)*fov;let a=p.a+cam;let dist=0,step=.025;while(dist<18&&!wall(p.x+Math.cos(a)*dist,p.y+Math.sin(a)*dist))dist+=step;let corrected=dist*Math.cos(cam);let wh=Math.min(H*1.4,H/(corrected*.82));let x=i*2;let shade=Math.max(20,145-corrected*8);ctx.fillStyle=`rgb(${Math.floor(shade*.25)},${Math.floor(shade*.65)},${Math.floor(shade*.8)})`;ctx.fillRect(x,horizon-wh/2,2,wh)}const objects=[...shards.map(s=>({...s,type:'shard'})),{...beacon,type:'beacon'},{...vault,type:'vault'}];objects.filter(o=>!o.taken).forEach(o=>{let dx=o.x-p.x,dy=o.y-p.y,d=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)-p.a;while(ang>Math.PI)ang-=Math.PI*2;while(ang<-Math.PI)ang+=Math.PI*2;if(Math.abs(ang)>fov*.62)return;let sx=W/2+Math.tan(ang)/(Math.tan(fov/2))*W/2;let size=Math.min(H*.7,H/(d*.65));let y=horizon-size*.5;ctx.globalAlpha=Math.max(.2,1-d/12);ctx.fillStyle=o.type==='shard'?'#62e8ff':o.type==='beacon'?'#b16cff':'#ffd166';ctx.shadowBlur=25;ctx.shadowColor=ctx.fillStyle;if(o.type==='shard'){ctx.beginPath();ctx.moveTo(sx,y);ctx.lineTo(sx+size*.18,y+size*.5);ctx.lineTo(sx,y+size);ctx.lineTo(sx-size*.18,y+size*.5);ctx.closePath();ctx.fill()}else{ctx.fillRect(sx-size*.12,y+size*.25,size*.24,size*.5)}ctx.shadowBlur=0;ctx.globalAlpha=1});ctx.fillStyle='rgba(255,255,255,.018)';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1);let vg=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.2,W/2,H/2,Math.max(W,H)*.75);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.65)');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H)}
function loop(t){let dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
updateHud();