const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const missionEl=document.getElementById('mission'),hintEl=document.getElementById('hint'),syncEl=document.getElementById('sync'),shardsEl=document.getElementById('shards'),levelEl=document.getElementById('level'),feedEl=document.getElementById('feed'),statusEl=document.getElementById('status');
let W,H,started=false,complete=false,last=0,keys={},turn=0,role='hacker',startedAt=0,distanceTravelled=0,interactionCount=0;
const map=Array.from({length:24},(_,y)=>Array.from({length:32},(_,x)=>{if(x===0||y===0||x===31||y===23)return '1';return '0'}));
function block(x1,y1,x2,y2){for(let y=y1;y<=y2;y++)for(let x=x1;x<=x2;x++)map[y][x]='1'}
// District boundaries + building blocks. Roads remain open for the player.
for(let y of [7,14])for(let x=1;x<31;x++)map[y][x]='1';
for(let x of [10,21])for(let y=1;y<23;y++)map[y][x]='1';
[[2,2,8,5],[13,2,18,5],[23,2,29,5],[2,9,8,12],[13,9,18,12],[23,9,29,12],[3,17,7,20],[10,17,14,20],[18,17,23,20],[26,17,29,20]].forEach(a=>block(...a));
// Openings in district roads.
[[5,7],[16,7],[26,7],[4,14],[16,14],[26,14],[10,4],[10,11],[10,18],[21,4],[21,11],[21,18]].forEach(([x,y])=>{map[y][x]='0';if(y===7||y===14){map[y][x+1]='0'}else{map[y+1][x]='0'}});
const shards=[{x:4.5,y:3.5,taken:false},{x:15.5,y:3.5,taken:false},{x:26.5,y:10.5,taken:false}];
const incidents=[{x:4.5,y:11.5,taken:false},{x:16.5,y:10.5,taken:false},{x:27.5,y:3.5,taken:false}];
const vault={x:6.5,y:11.5},extract={x:16.5,y:11.8},beacon={x:8.8,y:18.2};
const p={x:12.3,y:16.5,a:-Math.PI/2};let sync=0,level=1;
const agentListeners={};
function emit(name,detail={}){(agentListeners[name]||[]).forEach(fn=>fn(detail));window.dispatchEvent(new CustomEvent(`blocktrace:${name}`,{detail}))}
window.Blocktrace={getState:()=>({started,complete,role,sync,level,shards:getTargets().filter(s=>s.taken).length,position:{x:p.x,y:p.y},angle:p.a,distance:distanceTravelled,interactions:interactionCount,elapsed:startedAt?(performance.now()-startedAt)/1000:0}),on:(name,fn)=>{(agentListeners[name]??=[]).push(fn);return()=>agentListeners[name]=agentListeners[name].filter(x=>x!==fn)},setMission:t=>missionEl.textContent=t,setHint:t=>hintEl.textContent=t,log};
function getTargets(){return role==='defender'?incidents:shards}
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=innerWidth;H=innerHeight}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')interact()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('mousedown',()=>{canvas.requestPointerLock?.()});addEventListener('mousemove',e=>{if(started&&!complete&&document.pointerLockElement===canvas)p.a+=e.movementX*.0022});
function wall(x,y){const ix=Math.floor(x),iy=Math.floor(y);return iy<0||iy>=map.length||ix<0||ix>=map[0].length||map[iy][ix]==='1'}
function move(dx,dy){const r=.2,oldX=p.x,oldY=p.y;if(!wall(p.x+dx+r,p.y)&&!wall(p.x+dx-r,p.y))p.x+=dx;if(!wall(p.x,p.y+dy+r)&&!wall(p.x,p.y+dy-r))p.y+=dy;distanceTravelled+=Math.hypot(p.x-oldX,p.y-oldY)}
function interact(){if(!started||complete)return;interactionCount++;const targets=getTargets();const near=targets.find(s=>!s.taken&&Math.hypot(s.x-p.x,s.y-p.y)<.95);if(near){near.taken=true;sync=Math.min(100,sync+25);const n=targets.filter(s=>s.taken).length;level=Math.min(4,1+n);if(role==='hacker'){log('DATA SHARD EXTRACTED // encrypted payload secured','good');emit('shardRecovered',{count:n,position:{x:near.x,y:near.y}})}else{log('NODE STABILIZED // hostile simulation cleared','good');emit('nodeSecured',{count:n,position:{x:near.x,y:near.y}})}updateHud();return}
if(Math.hypot(beacon.x-p.x,beacon.y-p.y)<1.1){log('AGENT ARCOLOGY // city route recalculated','good');sync=Math.min(95,sync+10);emit('beaconSync',{sync});updateHud();return}
const terminal=role==='hacker'?extract:vault;if(Math.hypot(terminal.x-p.x,terminal.y-p.y)<1.1&&targets.every(s=>s.taken)){complete=true;document.getElementById('complete').classList.remove('hidden');document.getElementById('completeTitle').textContent=role==='hacker'?'Extraction Complete':'City Secured';document.getElementById('completeText').textContent=role==='hacker'?`All encrypted shards escaped the city. Trace stabilized at ${Math.round(sync)}% sync.`:`All three incidents were contained. Validator confidence reached ${Math.round(sync)}%.`;emit('complete',{sync,elapsed:startedAt?(performance.now()-startedAt)/1000:0});return}
const npc=window.BlocktraceCity?.npcs.find(n=>Math.hypot((n.renderX||n.x)-p.x,(n.renderY||n.y)-p.y)<1.05);if(npc)log(`${npc.name} // ${npc.role}: ${role==='hacker'?'Keep your trace quiet.':'Watch the dark routes. Someone is moving.'}`)}
function log(t,c=''){const d=document.createElement('div');d.className=c;d.textContent='> '+t;feedEl.prepend(d);while(feedEl.children.length>5)feedEl.lastChild.remove()}
function updateHud(){const targets=getTargets(),done=targets.filter(s=>s.taken).length;syncEl.textContent=Math.round(sync)+'%';shardsEl.textContent=done+' / 3';levelEl.textContent=level;const info=window.BlocktraceCity.roles[role];if(done===3){missionEl.textContent=role==='hacker'?'Reach extraction // DARK ALLEY':'Return to command // VAULT DISTRICT';hintEl.textContent=role==='hacker'?'Reach the pink extraction node and press E.':'Reach the purple command node and press E.'}else{missionEl.textContent=info.mission;hintEl.textContent=info.hint}}
function selectRole(next){role=next;document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('selected',b.dataset.role===role));const info=window.BlocktraceCity.roles[role];document.getElementById('roleTag').textContent=info.tag;document.getElementById('roleTitle').textContent=info.name;document.getElementById('roleDesc').textContent=info.hint;document.getElementById('startBtn').textContent=`ENTER AS ${info.name}`}
function start(){started=true;startedAt=performance.now();document.getElementById('start').classList.add('hidden');document.getElementById('roleSelect').classList.add('hidden');statusEl.textContent=`${role.toUpperCase()} ONLINE`;log(`CITY ONLINE // ${role.toUpperCase()} role initialized`,'good');log('AGENT // district map synchronized');log('MISSION 01 // '+window.BlocktraceCity.roles[role].mission);emit('start',{role});updateHud();canvas.requestPointerLock?.();requestAnimationFrame(loop)}
document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>selectRole(b.dataset.role)));document.getElementById('startBtn').onclick=start;document.getElementById('againBtn').onclick=()=>location.reload();selectRole('hacker');
function update(dt){if(!started||complete)return;let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),r=(keys.d?1:0)-(keys.a?1:0);if(keys.arrowleft)p.a-=dt*1.8;if(keys.arrowright)p.a+=dt*1.8;let sp=keys.shift?3.8:2.7,l=Math.hypot(f,r)||1;f/=l;r/=l;move((Math.cos(p.a)*f-Math.sin(p.a)*r)*sp*dt,(Math.sin(p.a)*f+Math.cos(p.a)*r)*sp*dt);sync=Math.min(100,sync+dt*.45);const district=window.BlocktraceCity.getDistrict(p.x,p.y);if(district&&turn%18===0)hintEl.textContent=`${district.name} // ${role==='hacker'?'Scout for weak signals.':'Scan for suspicious activity.'}`;turn++}
function render(){ctx.clearRect(0,0,W,H);const horizon=H*.52;let sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#030711');sky.addColorStop(1,'#0b1d2a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,horizon);let floor=ctx.createLinearGradient(0,horizon,0,H);floor.addColorStop(0,'#111923');floor.addColorStop(1,'#020408');ctx.fillStyle=floor;ctx.fillRect(0,horizon,W,H-horizon);
const rays=Math.ceil(W/3),fov=Math.PI/3;for(let i=0;i<rays;i++){const cam=(i/rays-.5)*fov,a=p.a+cam;let dist=0,step=.035;while(dist<24&&!wall(p.x+Math.cos(a)*dist,p.y+Math.sin(a)*dist))dist+=step;const corrected=dist*Math.cos(cam),wh=Math.min(H*1.5,H/(corrected*.72)),x=i*3,shade=Math.max(18,150-corrected*6);ctx.fillStyle=`rgb(${Math.floor(shade*.22)},${Math.floor(shade*.58)},${Math.floor(shade*.72)})`;ctx.fillRect(x,horizon-wh/2,3,wh)}
window.BlocktraceCity.tick(performance.now());const targets=getTargets().map(s=>({...s,type:role==='hacker'?'shard':'incident'}));const objects=[...targets,{...beacon,type:'beacon'},{...(role==='hacker'?extract:vault),type:'terminal'},...(window.BlocktraceCity.npcs||[]).map(n=>({...n,type:'npc'}))];objects.filter(o=>!o.taken).forEach(o=>{const dx=(o.renderX??o.x)-p.x,dy=(o.renderY??o.y)-p.y,d=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)-p.a;while(ang>Math.PI)ang-=Math.PI*2;while(ang<-Math.PI)ang+=Math.PI*2;if(Math.abs(ang)>fov*.66)return;const sx=W/2+Math.tan(ang)/(Math.tan(fov/2))*W/2,size=Math.min(H*.68,H/(d*.62)),y=horizon-size*.5;ctx.globalAlpha=Math.max(.18,1-d/18);let col=o.type==='shard'?'#62e8ff':o.type==='incident'?'#ff6b9d':o.type==='beacon'?'#b16cff':o.type==='terminal'?'#ffd166':'#7cf7c3';ctx.fillStyle=col;ctx.shadowBlur=o.type==='npc'?12:25;ctx.shadowColor=col;if(o.type==='shard'||o.type==='incident'){ctx.beginPath();ctx.moveTo(sx,y);ctx.lineTo(sx+size*.18,y+size*.5);ctx.lineTo(sx,y+size);ctx.lineTo(sx-size*.18,y+size*.5);ctx.closePath();ctx.fill()}else if(o.type==='npc'){ctx.beginPath();ctx.arc(sx,y+size*.55,size*.14,0,Math.PI*2);ctx.fill();ctx.fillRect(sx-size*.1,y+size*.62,size*.2,size*.3)}else{ctx.fillRect(sx-size*.13,y+size*.25,size*.26,size*.5)}ctx.shadowBlur=0;ctx.globalAlpha=1});
ctx.fillStyle='rgba(255,255,255,.018)';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1);const vg=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.2,W/2,H/2,Math.max(W,H)*.75);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.65)');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H)}
function loop(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}updateHud();
